---
- name: Deploy home configuration for current user
  hosts: localhost
  become: false
  vars:
    mkhome_configure_home: true
  roles:
    - firefox
    - chromium
    - micro
    - lf
    # - background
    # - desktop_apps
    # - fish
    #- git
    # - i3
    # - kitty
    # - lockscreen
    # - pulseaudio
    # - rofi
    # - screenlayout
    # - ssh
    # - timer
    # - tmux
    # - todo
    - vnc
    - workspaces
    # - x11
    # - xfce
