[Config]
Profiles=
	#build
	#containers
	#desktop
	#documentation
	#forensics
	#incus
	#ssh-server
	#vpn

Dependencies=base

[Build]
CacheDirectory=mkosi.cache/

[Output]
OutputDirectory=mkosi.output/
Format=disk

[Content]
BaseTrees=%O/base
CleanPackageMetadata=no

Packages=systemd-homed

Bootable=yes
UnifiedKernelImages=no
ShimBootloader=signed

Autologin=true

[Runtime]
Firmware=uefi-secure-boot
Console=gui
RAM=8G
CPUs=4
