[Config]
Dependencies=base

[Build]
CacheDirectory=mkosi.cache/

[Output]
OutputDirectory=mkosi.output/
Format=disk

[Content]
BaseTrees=%O/base
CleanPackageMetadata=no

Bootable=yes
UnifiedKernelImages=no
ShimBootloader=signed
Bootloader=grub-signed

Autologin=true

Packages=
	linux-image-generic
	grub-efi
	grub-efi-amd64
	grub-efi-amd64-signed
	tpm2-tools
	shim-signed
	systemd-boot
	systemd-homed

[Runtime]
Firmware=uefi-secure-boot
Console=gui
RAM=8G
CPUs=4
