---

- name: Debian packages
  apt:
    pkg:
      - xfce4
      - xfce4-goodies
      - xfce4-whiskermenu-plugin
      - xfce4-smartbookmark-plugin
      - xfce4-places-plugin
      - xfce4-datetime-plugin
      - xfce4-power-manager
      - xfce4-terminal

- name: xdg config
  copy:
    src: xdg/
    dest: /etc/xdg/

- name: xfce panel config
  template:
    src: xfce4-panel.xml.j2
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
  tags:
    - xfce-panel

- name: xfwm4 config
  template:
    src: xfwm4.xml.j2
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml

- name: default xsession manager
  community.general.alternatives:
    name: x-session-manager
    path: /usr/bin/xfce4-session
