[Content]
BaseTrees=%O/base
CleanPackageMetadata=no

Bootable=yes
UnifiedKernelImages=no
ShimBootloader=signed
Bootloader=grub-signed

Autologin=true

Packages=
	linux-image-generic
	grub-efi
	grub-efi-amd64
	grub-efi-amd64-signed
	tpm2-tools
	shim-signed
	systemd-boot
