[Content]
Packages=
	pipewire-audio
	pipewire
	pipewire-alsa
	pipewire-jack
	pipewire-pulse
	wireplumber
	vlc-plugin-pipewire
	pasystray
	pavucontrol
	audacity
	sound-juicer
	vlc
	vlc-l10n
	vlc-plugin-pipewire
	brasero
	obs-studio
	obs-cli
	obs-plugins
	obs-pipewire-audio-capture
