---

- name: workspace app service
  template:
    src: workspaces/workspace-app.service.j2
    dest: ~/.config/systemd/user/workspace-app@.service
    mode: 0755
  notify: systemd daemon-reload

- name: workspaces directory
  file:
    path: ~/.workspaces
    state: directory

- name: workspace directory
  file:
    path: ~/.workspaces/{{item.key}}
    state: directory
  with_dict: "{{ workspaces }}"
  when: workspaces | length > 0

- name: workspace focus scripts
  template:
    src: workspaces/workspace.focus.fish.j2
    dest: ~/.workspaces/{{item.key}}/focus
    mode: 0755
  with_dict: "{{ workspaces }}"
  when: workspaces | length > 0

- name: workspace space shortcut scripts
  template:
    src: workspaces/workspace.space.fish.j2
    dest: ~/.workspaces/{{item.key}}/space
    mode: 0755
  with_dict: "{{ workspaces }}"
  when:
    - workspaces | length > 0
    - item.value is defined
    - '"type" in item.value'
