[Content]
Packages=

    # DNS
	systemd-resolved
	bind9-dnsutils
	bind9-host

    # routing
	iproute2

	# diagnostics
	iputils-ping
	tcpdump
	nmap

	# cats
	ncat
	socat
    netcat-openbsd
    netcat-traditional

    # tunneling
    corkscrew
    magic-wormhole

	# clients
	telnet
    openssh-client
    curl
    rclone
