[Content]
Packages=
    git
    git-annex
    git-mediawiki
    git-lfs
    git-email
    git-credential-oauth
    git-delete-merged-branches
    git-delta
    git-extras
    git-flow
    gitbrute
    git-doc
    gitmagic
    gcli
    tig
    datalad
    bup
    subversion
