---

- name: Set kitty as the default terminal emulator
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/kitty
    link: /usr/bin/x-terminal-emulator

- name: Install kitty system-wide configuration
  template:
    src: kitty/kitty.conf.j2
    dest: /etc/xdg/kitty/kitty.conf
    mode: '0644'
  when: not (mkosi_build | default(false))