---
- name: Install debian packages
  apt:
    pkg: "{{ lookup('file', role_path + '/apt.txt') | regex_replace('#.*', '') | split('\n') | select('match', '^\\s*\\S+') | map('trim') | list }}"

# - name: Check if Zoom is already installed

# - name: Install Zoom deb package
#   apt:
#     deb: "{{ zoom_deb_url }}"
