---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
    scope: user

- name: reload i3
  shell: i3-msg reload
  when: i3_session is defined

- name: i3 reload
  shell: i3-msg reload  
  when: i3_session is defined

- name: xsession reload
  shell: i3-msg reload
  failed_when: false
